# Generated by Django 5.1.2 on 2024-10-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tabya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabyas', to='schedule.subcity')),
            ],
        ),
        migrations.CreateModel(
            name='SubcityWasteCollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waste_collection_schedule', to='schedule.subcity')),
                ('friday_afternoon', models.ManyToManyField(blank=True, related_name='friday_afternoon_collections', to='schedule.tabya')),
                ('friday_morning', models.ManyToManyField(blank=True, related_name='friday_morning_collections', to='schedule.tabya')),
                ('monday_afternoon', models.ManyToManyField(blank=True, related_name='monday_afternoon_collections', to='schedule.tabya')),
                ('monday_morning', models.ManyToManyField(blank=True, related_name='monday_morning_collections', to='schedule.tabya')),
                ('saturday_afternoon', models.ManyToManyField(blank=True, related_name='saturday_afternoon_collections', to='schedule.tabya')),
                ('saturday_morning', models.ManyToManyField(blank=True, related_name='saturday_morning_collections', to='schedule.tabya')),
                ('thursday_afternoon', models.ManyToManyField(blank=True, related_name='thursday_afternoon_collections', to='schedule.tabya')),
                ('thursday_morning', models.ManyToManyField(blank=True, related_name='thursday_morning_collections', to='schedule.tabya')),
                ('tuesday_afternoon', models.ManyToManyField(blank=True, related_name='tuesday_afternoon_collections', to='schedule.tabya')),
                ('tuesday_morning', models.ManyToManyField(blank=True, related_name='tuesday_morning_collections', to='schedule.tabya')),
                ('wednesday_afternoon', models.ManyToManyField(blank=True, related_name='wednesday_afternoon_collections', to='schedule.tabya')),
                ('wednesday_morning', models.ManyToManyField(blank=True, related_name='wednesday_morning_collections', to='schedule.tabya')),
            ],
        ),
    ]
