# Generated by Django 5.1.2 on 2024-10-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='kebele',
        ),
        migrations.AddField(
            model_name='issue',
            name='tabya',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='schedule.tabya'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='sub_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subcity'),
        ),
    ]
