# Generated by Django 5.0.6 on 2024-09-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='state',
            new_name='status',
        ),
    ]
