# Generated by Django 5.0.6 on 2024-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_state_useraccount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialprofile',
            name='position',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('RESIDENT', 'resident'), ('ADMIN', 'admin'), ('CITY', 'city'), ('SUB_CITY', 'sub_city'), ('TABYA', 'tabya'), ('DATA_ENCODER', 'data_encoder'), ('UNION', 'union')], max_length=15),
        ),
    ]
