# Generated by Django 5.0.6 on 2024-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_officialprofile_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['-date_joined'], 'permissions': [('can_create_users', 'Can create users')], 'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(upload_to='user_images/'),
        ),
    ]
