# Generated by Django 5.0.6 on 2024-09-25 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_options_alter_useraccount_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('sub_city', models.CharField(choices=[('semen', 'Semen'), ('hawelti', 'Hawelti'), ('ayder', 'Ayder'), ('adi_haki', 'Adi Haki'), ('kedemay_woyane', 'Kedemay Woyane'), ('hadnet', 'Hadnet'), ('kuiha', 'Kuiha')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TabyaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('sub_city', models.CharField(choices=[('semen', 'Semen'), ('hawelti', 'Hawelti'), ('ayder', 'Ayder'), ('adi_haki', 'Adi Haki'), ('kedemay_woyane', 'Kedemay Woyane'), ('hadnet', 'Hadnet'), ('kuiha', 'Kuiha')], max_length=50)),
                ('tabya', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
