# Generated by Django 5.0.6 on 2024-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_subcityprofile_tabyaprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unionprofile',
            name='union_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
