# Generated by Django 5.0.6 on 2024-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_unionprofile_union_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='subcityprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='tabyaprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
