# Generated by Django 5.1.2 on 2024-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_officialprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
