# Generated by Django 5.1.2 on 2024-10-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_useraccount_image'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='sub_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subcity'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='tabya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.tabya'),
        ),
        migrations.AlterField(
            model_name='subcityprofile',
            name='sub_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subcity'),
        ),
        migrations.AlterField(
            model_name='tabyaprofile',
            name='sub_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subcity'),
        ),
        migrations.AlterField(
            model_name='tabyaprofile',
            name='tabya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.tabya'),
        ),
        migrations.AlterField(
            model_name='unionprofile',
            name='sub_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subcity'),
        ),
    ]
