# Generated by Django 5.0.6 on 2024-09-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentWasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=50)),
                ('metric_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sub_city', models.CharField(choices=[('semen', 'Semen'), ('hawelti', 'Hawelti'), ('ayder', 'Ayder'), ('adi_haki', 'Adi Haki'), ('kedemay_woyane', 'Kedemay Woyane'), ('hadnet', 'Hadnet'), ('kuiha', 'Kuiha')], max_length=50)),
                ('tabya', models.CharField(max_length=100)),
                ('tabya_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('tabya_approval_date', models.DateTimeField(blank=True, null=True)),
                ('tabya_rejection_reason', models.TextField(blank=True, null=True)),
                ('union_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('union_approval_date', models.DateTimeField(blank=True, null=True)),
                ('union_rejection_reason', models.TextField(blank=True, null=True)),
                ('city_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('city_approval_date', models.DateTimeField(blank=True, null=True)),
                ('report_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('delivering_union', models.ForeignKey(limit_choices_to={'role': 'UNION'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_reports', to=settings.AUTH_USER_MODEL)),
                ('receiver_data_encoder', models.ForeignKey(limit_choices_to={'role': 'DATA_ENCODER'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('tabya_approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'TABYA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabya_approved_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
