# Generated by Django 5.1.2 on 2024-10-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentwastereport',
            old_name='tabya_rejection_reason',
            new_name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='residentwastereport',
            name='union_rejection_reason',
        ),
    ]
