# Generated by Django 5.1.2 on 2024-10-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_tabya_rejection_reason_residentwastereport_rejection_reason_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentwastereport',
            name='sub_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to='schedule.subcity'),
        ),
        migrations.AlterField(
            model_name='residentwastereport',
            name='tabya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to='schedule.tabya'),
        ),
    ]
