# Generated by Django 5.2.8 on 2025-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_residentwastereport_sub_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentwastereport',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
