# Generated by Django 4.2 on 2024-05-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
